pembekalan_net/pembekalan_net/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using pembekalan_net.datamodels;
using pembekalan_net.Services;
using pembekalan_net.viewmodels;

namespace pembekalan_net.Controllers
{
    public class AuthController : Controller
    {
        private AuthService authService;
        private Role2Service role2Service;
        VMResponse respon = new VMResponse();

        public AuthController(Role2Service _role2Service, AuthService _authService)
        {
            role2Service = _role2Service;
            authService = _authService;
        }

        public IActionResult Login()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> LoginSubmit(string email, string password)
        {
            VMTblCustomer customer = await authService.CheckLogin(email, password);

            if(customer != null)
            {
                respon.Message = $"Hello, {customer.NameCustomer} Welcome to Pembekalan .Net";
                HttpContext.Session.SetString("NameCustomer", customer.NameCustomer);
                HttpContext.Session.SetInt32("IdCustomer", customer.Id);
                HttpContext.Session.SetInt32("IdRole", customer.IdRole ?? 0);
            }
            else
            {
                respon.Success = false;
                respon.Message = $"Oops, {email} not found or password is wrong, please check it!";
            }

            return Json(new { dataRespon = respon });
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Register()
        {
            List<TblRole> listRole = await role2Service.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView();
        }


    }
}

pembekalan_net/pembekalan_net/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using pembekalan_net.datamodels;
using pembekalan_net.Services;
using pembekalan_net.viewmodels;

namespace pembekalan_net.Controllers
{
    public class CustomerController : Controller
    {
        private Role2Service role2Service;
        private CustomerService customerService;

        public CustomerController(Role2Service _role2Service, CustomerService _customerService)
        {
            role2Service = _role2Service;
            customerService = _customerService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString,
                                                string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            sortOrder = sortOrder ?? "";
            ViewBag.NameSort = sortOrder == "name" ? "name_desc" : "name";
            ViewBag.CustomerSort = sortOrder == "customer" ? "customer_desc" : "customer";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMTblCustomer> data = await customerService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCustomer.ToLower().Contains(searchString.ToLower())
                    || a.Email.ToLower().Contains(searchString.ToLower())
                    || a.RoleName.ToLower().Contains(searchString.ToLower())
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "customer_desc":
                    data = data.OrderByDescending(a => a.NameCustomer).ToList();
                    break;
                case "customer":
                    data = data.OrderBy(a => a.NameCustomer).ToList();
                    break;
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                case "name":
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<VMTblCustomer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            List<TblRole> listRole = await role2Service.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView();
        }

        //public async Task<IActionResult> CheckEmailIsExist(string email, int id) //Sama saja
        public async Task<JsonResult> CheckEmailIsExist(string email, int id)
        {
            bool isExist = await customerService.CheckEmailIsExist(email, id);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblCustomer dataParam)
        {
            VMResponse respon = await customerService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);

            List<TblRole> listRole = await role2Service.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblCustomer dataParam)
        {
            VMResponse respon = await customerService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await customerService.Delete(id);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> MultipleDelete(List<int> listId)
        {
            List<string> listName = new List<string>();
            foreach (int item in listId)
            {
                VMTblCustomer data = await customerService.GetDataById(item);
                listName.Add(data.NameCustomer);
            }
            ViewBag.ListName = listName;

            return PartialView();
        }

        [HttpPost]
        public async Task<IActionResult> SureMultipleDelete(List<int> listId)
        {
            VMResponse respon = await customerService.MultipleDelete(listId);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }



    }
}

pembekalan_net/pembekalan_net/Controllers/Role2Controller.cs
using Microsoft.AspNetCore.Mvc;
using pembekalan_net.datamodels;
using pembekalan_net.Services;
using pembekalan_net.viewmodels;

namespace pembekalan_net.Controllers
{
    public class Role2Controller : Controller
    {
        private Role2Service role2Service;

        public Role2Controller(Role2Service _role2Service)
        {
            role2Service = _role2Service;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString,
                                                string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if(searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<TblRole> data = await role2Service.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())
                    ).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        public async Task<JsonResult> CheckNameIsExist(string roleName, int id)
        {
            bool isExist = await role2Service.CheckNameIsExist(roleName, id);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblRole dataParam)
        {
            VMResponse respon = await role2Service.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            TblRole data = await role2Service.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TblRole dataParam)
        {
            VMResponse respon = await role2Service.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            TblRole data = await role2Service.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TblRole data = await role2Service.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await role2Service.Delete(id);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }


    }
}

pembekalan_net/pembekalan_net/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using pembekalan_net.datamodels;
using pembekalan_net.Services;
using pembekalan_net.viewmodels;

namespace pembekalan_net.Controllers
{
    public class RoleController : Controller
    {
        //private readonly pembekalan_netContext db;
        private readonly RoleService roleService;

        //public RoleController(pembekalan_netContext _db)
        public RoleController(RoleService _roleService)
        {
            roleService = _roleService;
            //db = _db;
            //roleService = new RoleService(db);
        }

        public IActionResult Index()
        {
            List<VMTblRole> dataView = roleService.GetAllData();
            ViewBag.listRole = dataView;
            return View(dataView);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Create(VMTblRole dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = roleService.Create(dataView);

                if (respon.Success)
                {
                    return RedirectToAction("Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblRole dataView = roleService.GetById(id);
            return PartialView(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblRole dataView)
        {
            VMResponse respon = new VMResponse();

            if (ModelState.IsValid)
            {
                respon = roleService.Edit(dataView);

                if (respon.Success)
                {
                    return Redirect("/Role/Index");
                }
            }

            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblRole dataView = roleService.GetById(id);
            return PartialView(dataView);
        }

        public IActionResult Delete(int id)
        {
            VMTblRole dataView = roleService.GetById(id);
            return PartialView(dataView);
        }

        [HttpPost]
        public IActionResult Delete(VMTblRole dataView)
        {
            VMResponse respon = new VMResponse();

            respon = roleService.Delete(dataView);

            if (respon.Success)
            {
                return Redirect("/Role/Index");
            }

            return View(respon.Entity);
        }


    }
}

pembekalan_net/pembekalan_net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/adminmart/assets/images/favicon.png">
    <title>Adminmart Template - The Ultimate Multipurpose admin template</title>
    <!-- JQuery -->
    <script src="~/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <!-- Custom CSS -->
    <link href="~/adminmart/assets/extra-libs/c3/c3.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/libs/chartist/dist/chartist.min.css" rel="stylesheet">
    <link href="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/adminmart/dist/css/style.min.css" rel="stylesheet">

    <!-- Sweetalert2 -->
    <script src="~/adminmart/plugins/sweetalert2/sweetalert2.js"></script>

    <!-- Toastr -->
    <script src="~/adminmart/plugins/toastr/toastr.min.js"></script>
    <link href="~/adminmart/plugins/toastr/toastr.css" rel="stylesheet">

</head>
<body>

    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
        data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">

        <partial name="_Header" />
        <partial name="_Sidebar" />
    
        <div class="page-wrapper">

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        

            <footer class="footer text-center text-muted">
                All Rights Reserved by Adminmart. Designed and Developed by <a
                    href="https://wrappixel.com">WrapPixel</a>.
            </footer>

        </div>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" id="modal_body">
            ...
          </div>
          @*<div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>*@
        </div>
      </div>
    </div>


    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    @*<script src="~/adminmart/assets/libs/jquery/dist/jquery.min.js"></script>*@
    <script src="~/adminmart/assets/libs/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/adminmart/assets/libs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- apps -->
    <!-- apps -->
    <script src="~/adminmart/dist/js/app-style-switcher.js"></script>
    <script src="~/adminmart/dist/js/feather.min.js"></script>
    <script src="~/adminmart/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js"></script>
    <script src="~/adminmart/dist/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="~/adminmart/dist/js/custom.min.js"></script>
    <!--This page JavaScript -->
    <script src="~/adminmart/assets/extra-libs/c3/d3.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/c3/c3.min.js"></script>
    <script src="~/adminmart/assets/libs/chartist/dist/chartist.min.js"></script>
    <script src="~/adminmart/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/adminmart/assets/extra-libs/jvector/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/adminmart/dist/js/pages/dashboards/dashboard1.min.js"></script>

</body>
</html>

pembekalan_net/pembekalan_net/Views/Shared/_LayoutOld.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - pembekalan_net</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/pembekalan_net.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">pembekalan_net</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - pembekalan_net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    <!-- Modal -->
    <div class="modal fade" id="my_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="modal_body">
            ...
          </div>
          
        </div>
      </div>
    </div>


    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

pembekalan_net/pembekalan_net/Views/Shared/_Sidebar.cshtml
@using pembekalan_net.Services

@inject AuthService authService

@{
    int IdCustomer = @Context.Session.GetInt32("IdCustomer") ?? 0;
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
    var menus = await authService.MenuAccess(IdRole);
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">

    @*
    @if (IdCustomer != 0)
    {
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="sidebar-item"> <a class="sidebar-link sidebar-link" href="index.html"
                            aria-expanded="false"><i data-feather="home" class="feather-icon"></i><span
                                class="hide-menu">Dashboard</span></a></li>
                    <li class="list-divider"></li>
                    <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                    <li class="sidebar-item"> <a class="sidebar-link" asp-controller="Role" asp-action="Index"
                            aria-expanded="false"><i data-feather="tag" class="feather-icon"></i><span
                                class="hide-menu">Role</span></a></li>
                    <li class="sidebar-item"> <a class="sidebar-link sidebar-link" asp-controller="Role2" asp-action="Index"
                            aria-expanded="false"><i data-feather="message-square" class="feather-icon"></i><span
                                class="hide-menu">Role (JQuery Val)</span></a></li>
                    <li class="sidebar-item"> <a class="sidebar-link sidebar-link" asp-controller="Customer" asp-action="Index"
                            aria-expanded="false"><i data-feather="calendar" class="feather-icon"></i><span
                                class="hide-menu">Customer</span></a></li>


                    <li class="list-divider"></li>

                    <li class="sidebar-item"> <a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout"
                            aria-expanded="false"><i data-feather="log-out" class="feather-icon"></i><span
                                class="hide-menu">Logout</span></a></li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->

    }
    *@


    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
            
                @foreach (var parent in menus)
                {
                    <li class="sidebar-item"> <a class="sidebar-link has-arrow" href="javascript:void(0)"
                            aria-expanded="false"><i data-feather="@parent.MenuIcon" class="feather-icon"></i>
                            <span class="hide-menu">@parent.MenuName</span></a>
                        <ul aria-expanded="false" class="collapse first-level base-level-line">

                        @foreach (var child in parent.ListChild)
                        {
                            <li class="sidebar-item">
                                <a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="sidebar-link">
                                <span class="hide-menu">@child.MenuName</span></a>
                            </li>
                        }

                        </ul>
                    </li>
                }

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->



</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->